---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove ess-image
      command: docker rmi triple3a/ess-page
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t triple3a/ess-page .

    - name: Push Image to dockerhub
      command: docker push triple3a/ess-page

    - name: run container
      command: docker run -d --name web-container -p 5000:80 triple3a/ess-page